import React from 'react';
import { useApp } from '../context/AppContext';
import { FileText, Download, FileSpreadsheet, File } from 'lucide-react';
import { exportToCSV, exportToExcel, exportToPDF } from '../utils/exporter';
import { formatCurrency } from '../utils/formatters';

export const ReportsView: React.FC = () => {
  const { db, company, showToast } = useApp();

  if (!db || !company) return null;

  const handleExportFullSystemPDF = () => {
    exportToPDF(
      `${company.name} Full Executive Operating Report`,
      'Generated by Founder Decision Operating System',
      [
        { heading: '1. Financial Snapshot', content: `Monthly Revenue: ${formatCurrency(company.monthlyRevenue)} | Monthly Expenses: ${formatCurrency(company.monthlyExpenses)} | Cash Balance: ${formatCurrency(company.cashBalance)} | Runway: ${company.runwayMonths} Months` },
        { heading: '2. Customer Accounts & CRM', content: `Total Customers Managed: ${db.customers.length} | Active Leads in Pipeline: ${db.customers.filter((c) => c.leadStatus !== 'Closed Won').length}` },
        { heading: '3. Team & Task Sprint Velocity', content: `Employees Onboarded: ${db.employees.length} | Sprint Tasks Completed: ${db.tasks.filter((t) => t.status === 'Done').length}` },
        { heading: '4. Active Operational Risks', content: `Risks Monitored: ${db.risks.filter((r) => r.status === 'Active').length} Active Items` },
      ]
    );
    showToast('Downloaded Full Operating PDF Report!');
  };

  return (
    <div className="space-y-6 pb-12 animate-fade-in max-w-4xl mx-auto">
      {/* Header */}
      <div>
        <h1 className="text-2xl font-bold text-slate-900 dark:text-slate-100 tracking-tight flex items-center gap-2">
          <FileText className="w-7 h-7 text-indigo-500" /> Executive Reports & Data Exports
        </h1>
        <p className="text-sm text-slate-500">
          Generate printable PDF summaries, Excel financial sheets, and raw CSV dumps of your startup database.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {/* Report Card 1 */}
        <div className="p-6 rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-sm space-y-4">
          <div className="p-3 rounded-xl bg-indigo-50 dark:bg-indigo-950 w-fit text-indigo-600">
            <FileText className="w-6 h-6" />
          </div>
          <div>
            <h3 className="text-base font-bold text-slate-900 dark:text-slate-100">Full System Executive PDF Report</h3>
            <p className="text-xs text-slate-500 mt-1">
              Includes Revenue P&L, Customer CRM, Team Velocity, and Active Risk summaries in a printable PDF format.
            </p>
          </div>
          <button
            onClick={handleExportFullSystemPDF}
            className="w-full py-2.5 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white font-semibold text-xs transition-all flex items-center justify-center gap-2"
          >
            <Download className="w-4 h-4" /> Export Executive PDF
          </button>
        </div>

        {/* Report Card 2 */}
        <div className="p-6 rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-sm space-y-4">
          <div className="p-3 rounded-xl bg-emerald-50 dark:bg-emerald-950 w-fit text-emerald-600">
            <FileSpreadsheet className="w-6 h-6" />
          </div>
          <div>
            <h3 className="text-base font-bold text-slate-900 dark:text-slate-100">Full Financials Excel Workbook</h3>
            <p className="text-xs text-slate-500 mt-1">
              Complete multi-sheet workbook containing raw line items for revenue, vendor expenses, payroll, and funding rounds.
            </p>
          </div>
          <button
            onClick={() => {
              exportToExcel('Financials_Master_Workbook', 'Revenue', db.revenue);
              showToast('Exported Master Excel Workbook!');
            }}
            className="w-full py-2.5 rounded-xl bg-emerald-600 hover:bg-emerald-500 text-white font-semibold text-xs transition-all flex items-center justify-center gap-2"
          >
            <Download className="w-4 h-4" /> Export Excel Workbook
          </button>
        </div>

        {/* Report Card 3 */}
        <div className="p-6 rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-sm space-y-4">
          <div className="p-3 rounded-xl bg-sky-50 dark:bg-sky-950 w-fit text-sky-600">
            <File className="w-6 h-6" />
          </div>
          <div>
            <h3 className="text-base font-bold text-slate-900 dark:text-slate-100">Customer CRM CSV Export</h3>
            <p className="text-xs text-slate-500 mt-1">
              Dump all 500 customer records, deal values, and pipeline statuses into clean CSV for external CRM imports.
            </p>
          </div>
          <button
            onClick={() => {
              exportToCSV('Customers_CRM_Dump', db.customers);
              showToast('Exported Customer CRM CSV!');
            }}
            className="w-full py-2.5 rounded-xl bg-sky-600 hover:bg-sky-500 text-white font-semibold text-xs transition-all flex items-center justify-center gap-2"
          >
            <Download className="w-4 h-4" /> Export CRM CSV
          </button>
        </div>

        {/* Report Card 4 */}
        <div className="p-6 rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-sm space-y-4">
          <div className="p-3 rounded-xl bg-purple-50 dark:bg-purple-950 w-fit text-purple-600">
            <FileSpreadsheet className="w-6 h-6" />
          </div>
          <div>
            <h3 className="text-base font-bold text-slate-900 dark:text-slate-100">Employee & Payroll CSV Export</h3>
            <p className="text-xs text-slate-500 mt-1">
              Export employee list with salaries, departments, net pay, and productivity scores.
            </p>
          </div>
          <button
            onClick={() => {
              exportToCSV('Payroll_Register_Dump', db.payroll);
              showToast('Exported Payroll CSV!');
            }}
            className="w-full py-2.5 rounded-xl bg-purple-600 hover:bg-purple-500 text-white font-semibold text-xs transition-all flex items-center justify-center gap-2"
          >
            <Download className="w-4 h-4" /> Export Payroll CSV
          </button>
        </div>
      </div>
    </div>
  );
};
